# hapi.application.yaml (located at project root)
spring:
  datasource:
    # Connects to the dedicated PostgreSQL container for HAPI FHIR using service name fhir-db
    url: 'jdbc:postgresql://fhir-db:5432/hapi_fhir_db' # Database name set to hapi_fhir_db
    username: hapi_fhir_user
    password: hapi_fhir_password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.hbm2ddl.auto: update