// src/types/patient.ts

// Type definitions for patient-related data structures

/**
 * Interface representing a patient entity.
 */
export interface Patient {
   /** Unique identifier for the patient (auto-generated by the database) */
   id: number
   pid: string // Patient identifier (e.g., personal ID number)
   active: boolean // Indicates if the patient is active
   familyName: string // Patient's family name
   givenName: string // Patient's given name
   telecom: string // Contact phone number
   gender: 'Male' | 'Female' | 'Others' // Gender ('male', 'female', 'other' in Chinese)
   birthday: string // Date of birth (string format)
   address: string // Residential address
   email?: string // Optional: Email address
   postalCode?: string // Optional: Postal code
   country?: string // Optional: Country of residence
   preferredLanguage?: string // Optional: Preferred language
   emergencyContactName?: string // Optional: Name of emergency contact
   emergencyContactRelationship?: string // Optional: Relationship to emergency contact
   emergencyContactPhone?: string // Optional: Phone number of emergency contact
}

/**
 * Type alias for creating a new patient, excluding the auto-generated 'id' field.
 */
export type NewPatient = Omit<Patient, 'id'>
